(function () {
  "use strict";

  var CATEGORIES = [
    { id: "apple", title: "Apple" },
    { id: "android", title: "Android" }
  ];

  var HIDDEN_OLD_SEEDS = { "updating-apps": true, "free-promo-month": true };

  var SEEDS = [
    {
      seed_key: "updating-apps-apple",
      title: "Updating Apps",
      summary: "Ship an iOS update: archive from Xcode, then create the App Store Connect version and submit for review.",
      category: "apple",
      link_title: "",
      link_url: "",
      sort_order: 0,
      steps: [
        "## Open Xcode on MacBook",
        "Select any iOS device.",
        "Click Archive.",
        "Distribute app.",
        "Click App Store Connect, then click Distribute.",
        "Click Done. Status should say “uploaded to Apple.”",
        "## Open App Store Connect in the browser",
        "Click the app you are updating.",
        "Click the plus button (top left under the app name).",
        "Type the version number (must match the Xcode version number).",
        "Enter the What’s New description.",
        "Click Add Build.",
        "Click Save.",
        "Click Add for Review, then click Submit for Review."
      ]
    },
    {
      seed_key: "free-promo-apple",
      title: "Adding a Free or Promo Month",
      summary: "Done in App Store Connect — no code change.",
      category: "apple",
      link_title: "",
      link_url: "",
      sort_order: 1,
      steps: [
        "## App Store Connect",
        "Open Subscriptions.",
        "Open Introductory offer.",
        "Choose Free 1 month.",
        "Set Eligibility to new subscribers."
      ]
    },
    {
      seed_key: "updating-apps-android",
      title: "Updating Apps",
      summary: "Ship an Android update: generate a signed bundle, then create the Play Console release and submit for review.",
      category: "android",
      link_title: "",
      link_url: "",
      sort_order: 10,
      steps: [
        "## Open Android Studio on MacBook",
        "Sync Gradle (if needed).",
        "Select Build Variant — release.",
        "Click Build → Generate Signed Bundle / APK.",
        "Click Android App Bundle.",
        "Click Next, then click Create.",
        "## Open Google Play Console in the browser",
        "Click the app you are updating.",
        "Click Test and release → Production.",
        "Click Create new release (top right).",
        "Upload the new .aab file generated by Android Studio.",
        "Confirm the version numbers are correct.",
        "Click Next after the release is uploaded → Save → Go to publishing overview.",
        "Wait on the quick check, then click Submit for review."
      ]
    },
    {
      seed_key: "free-promo-android",
      title: "Adding a Free or Promo Month",
      summary: "Done in Google Play Console — no code change.",
      category: "android",
      link_title: "",
      link_url: "",
      sort_order: 11,
      steps: [
        "## Google Play Console",
        "Open Monetize → Products.",
        "Open Subscriptions → Add offer.",
        "Choose Free trial — phase — 1 month.",
        "Set Eligibility to new customer.",
        "Activate offer."
      ]
    }
  ];

  var root = null;
  var db = null;
  var guides = [];
  var selectedId = null;
  var checkedSteps = {};
  var editing = false;
  var dirty = false;
  var saving = false;

  function el(name) {
    return root ? root.querySelector('[data-el="' + name + '"]') : null;
  }

  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function trim(s) {
    return String(s == null ? "" : s).trim();
  }

  function showMsg(msg, ok) {
    var box = el("banner");
    if (!box) return;
    box.textContent = msg || "";
    box.classList.toggle("is-on", !!msg);
    box.classList.toggle("is-ok", !!ok);
    box.classList.toggle("is-bad", !!msg && !ok);
  }

  function syncSave() {
    var btn = document.getElementById("global-save");
    if (!btn) return;
    btn.classList.remove("hidden");
    btn.disabled = !dirty || saving || !editing;
    btn.textContent = saving ? "Saving…" : "Save";
  }

  function hideSave() {
    var btn = document.getElementById("global-save");
    if (!btn) return;
    btn.classList.add("hidden");
    btn.disabled = true;
  }

  function markDirty() {
    dirty = true;
    syncSave();
    showMsg("Unsaved changes", true);
  }

  function clearDirty() {
    dirty = false;
    syncSave();
  }

  function categoryTitle(id) {
    var hit = CATEGORIES.filter(function (c) { return c.id === id; })[0];
    return hit ? hit.title : "Other";
  }

  function normalizeSteps(raw) {
    if (Array.isArray(raw)) return raw.map(String);
    if (typeof raw === "string") {
      try {
        var parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed.map(String);
      } catch (e) {}
      return raw.split(/\n/).map(function (line) { return line.trim(); }).filter(Boolean);
    }
    return [];
  }

  function isHiddenOldSeed(guide) {
    return !!(guide.seed_key && HIDDEN_OLD_SEEDS[guide.seed_key]);
  }

  function groupOf(guide) {
    var c = guide.category || "";
    if (c === "android" || c === "googlePlay" || c === "androidStudio") return "android";
    return "apple";
  }

  function guidesIn(category) {
    return guides.filter(function (g) {
      if (isHiddenOldSeed(g)) return false;
      return groupOf(g) === category;
    }).sort(function (a, b) {
      if (a.sort_order !== b.sort_order) return a.sort_order - b.sort_order;
      return String(a.title || "").localeCompare(String(b.title || ""));
    });
  }

  function visibleGuides() {
    return guidesIn("apple").concat(guidesIn("android"));
  }

  function selected() {
    return guides.filter(function (g) { return g.id === selectedId; })[0] || null;
  }

  function shell() {
    return (
      '<div class="sop-workspace">' +
        '<p class="status sop-banner" data-el="banner"></p>' +
        '<div class="sop-split">' +
          '<aside class="sop-list" data-el="list"></aside>' +
          '<section class="sop-detail" data-el="detail"></section>' +
        "</div>" +
      "</div>"
    );
  }

  function listItem(guide) {
    var steps = normalizeSteps(guide.steps);
    var stepCount = steps.filter(function (s) { return s.indexOf("## ") !== 0; }).length;
    return (
      '<button type="button" class="sop-item' + (guide.id === selectedId ? " is-on" : "") + '" data-id="' + guide.id + '">' +
        "<strong>" + esc(guide.title || "New SOP") + "</strong>" +
        "<span>" + stepCount + " step" + (stepCount === 1 ? "" : "s") + "</span>" +
      "</button>"
    );
  }

  function renderList() {
    var apple = guidesIn("apple");
    var android = guidesIn("android");
    var html = "<h2>How-to</h2>";
    html += '<div class="sop-group-label">Apple</div>';
    if (!apple.length) html += '<p class="sop-empty-group">No Apple SOPs yet.</p>';
    apple.forEach(function (guide) { html += listItem(guide); });
    html += '<div class="sop-group-bar" aria-hidden="true"></div>';
    html += '<div class="sop-group-label">Android</div>';
    if (!android.length) html += '<p class="sop-empty-group">No Android SOPs yet.</p>';
    android.forEach(function (guide) { html += listItem(guide); });
    html += '<button type="button" class="sop-add" data-el="add">+ Add SOP</button>';
    el("list").innerHTML = html;
    el("list").querySelectorAll("[data-id]").forEach(function (btn) {
      btn.onclick = function () {
        if (dirty && editing && !window.confirm("You have unsaved edits. Leave without saving?")) return;
        selectedId = btn.getAttribute("data-id");
        checkedSteps = {};
        editing = false;
        clearDirty();
        render();
      };
    });
    var add = el("add");
    if (add) add.onclick = addGuide;
  }

  function renderDetail() {
    var guide = selected();
    var detail = el("detail");
    if (!guide) {
      detail.innerHTML =
        '<div class="sop-detail-empty"><div><h1>SOP</h1><p>Pick a how-to on the left.</p></div></div>';
      return;
    }

    if (editing) {
      detail.innerHTML =
        '<div class="sop-edit">' +
          "<h1>Edit SOP</h1>" +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Title</label>' +
          '<input data-el="edit-title" type="text" value="' + esc(guide.title || "") + '" />' +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Summary</label>' +
          '<input data-el="edit-summary" type="text" value="' + esc(guide.summary || "") + '" />' +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Category</label>' +
          '<select data-el="edit-category">' +
            CATEGORIES.map(function (c) {
              return '<option value="' + c.id + '"' + (guide.category === c.id ? " selected" : "") + ">" + esc(c.title) + "</option>";
            }).join("") +
          "</select>" +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Steps (one per line; start a section with ## )</label>' +
          '<textarea data-el="edit-steps">' + esc(normalizeSteps(guide.steps).join("\n")) + "</textarea>" +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Link title</label>' +
          '<input data-el="edit-link-title" type="text" value="' + esc(guide.link_title || "") + '" />' +
          '<label style="font-size:11px;font-weight:700;color:#6b7388">Link URL</label>' +
          '<input data-el="edit-link-url" type="text" value="' + esc(guide.link_url || "") + '" />' +
          '<div class="sop-actions">' +
            '<button class="btn btn-ghost" type="button" data-el="cancel-edit">Cancel</button>' +
          "</div>" +
        "</div>";
      detail.querySelectorAll("input, textarea, select").forEach(function (input) {
        input.addEventListener("input", markDirty);
        input.addEventListener("change", markDirty);
      });
      el("cancel-edit").onclick = function () {
        if (dirty && !window.confirm("Discard edits?")) return;
        editing = false;
        clearDirty();
        render();
      };
      syncSave();
      return;
    }

    var steps = normalizeSteps(guide.steps);
    var html =
      "<h1>" + esc(guide.title || "New SOP") + "</h1>" +
      (trim(guide.summary) ? '<p class="sop-summary">' + esc(guide.summary) + "</p>" : "") +
      '<div class="sop-meta">' +
        '<span class="sop-badge">' + esc(categoryTitle(guide.category)) + "</span>" +
        (trim(guide.link_url)
          ? '<a class="sop-link" href="' + esc(guide.link_url) + '" target="_blank" rel="noopener">' +
            esc(guide.link_title || guide.link_url) + "</a>"
          : "") +
      "</div>";

    steps.forEach(function (step, index) {
      if (step.indexOf("## ") === 0) {
        html += '<div class="sop-section-title">' + esc(step.slice(3)) + "</div>";
        return;
      }
      var done = !!checkedSteps[index];
      html +=
        '<label class="sop-step' + (done ? " is-done" : "") + '">' +
          '<input type="checkbox" data-step="' + index + '"' + (done ? " checked" : "") + " />" +
          "<p>" + esc(step) + "</p>" +
        "</label>";
    });

    html +=
      '<div class="sop-actions">' +
        '<button class="btn btn-ghost" type="button" data-el="edit">Edit</button>' +
        '<button class="btn btn-ghost" type="button" data-el="reset-checks">Clear checks</button>' +
        '<button class="btn btn-ghost" type="button" data-el="delete">Remove</button>' +
      "</div>";

    detail.innerHTML = html;
    detail.querySelectorAll("[data-step]").forEach(function (input) {
      input.onchange = function () {
        checkedSteps[Number(input.getAttribute("data-step"))] = input.checked;
        renderDetail();
      };
    });
    el("edit").onclick = function () {
      editing = true;
      dirty = false;
      syncSave();
      renderDetail();
    };
    el("reset-checks").onclick = function () {
      checkedSteps = {};
      renderDetail();
    };
    el("delete").onclick = function () {
      if (!window.confirm('Remove "' + (guide.title || "SOP") + '"?')) return;
      db.from("sop_guides").delete().eq("id", guide.id).then(function (res) {
        if (res.error) return showMsg(res.error.message, false);
        guides = guides.filter(function (g) { return g.id !== guide.id; });
        selectedId = null;
        ensureSelection();
        render();
      });
    };
  }

  function render() {
    renderList();
    renderDetail();
    syncSave();
  }

  function ensureSelection() {
    var list = visibleGuides();
    if (selectedId && list.some(function (g) { return g.id === selectedId; })) return;
    selectedId = list[0] ? list[0].id : null;
  }

  function addGuide() {
    db.from("sop_guides").insert({
      title: "New SOP",
      summary: "",
      category: (selected() && selected().category) || "apple",
      steps: ["First step"],
      sort_order: (guides.map(function (g) { return g.sort_order; }).sort(function (a, b) { return b - a; })[0] || 0) + 1
    }).select("*").single().then(function (res) {
      if (res.error) {
        showMsg(/does not exist|schema cache/i.test(res.error.message || "")
          ? "Run sql/010_sop.sql in Supabase, then refresh."
          : res.error.message, false);
        return;
      }
      guides.push(res.data);
      selectedId = res.data.id;
      editing = true;
      clearDirty();
      render();
      showMsg("SOP added. Edit, then Save.", true);
    });
  }

  function saveAll() {
    if (!editing || saving || !dirty) return;
    var guide = selected();
    if (!guide) return;
    saving = true;
    syncSave();
    showMsg("Saving…", true);
    var title = el("edit-title").value;
    var summary = el("edit-summary").value;
    var category = el("edit-category").value;
    var steps = el("edit-steps").value.split(/\n/).map(function (line) { return line.trimEnd(); }).filter(function (line) { return line.trim(); });
    var linkTitle = el("edit-link-title").value;
    var linkUrl = el("edit-link-url").value;
    db.from("sop_guides").update({
      title: title,
      summary: summary,
      category: category,
      steps: steps,
      link_title: linkTitle,
      link_url: linkUrl
    }).eq("id", guide.id).select("*").single().then(function (res) {
      saving = false;
      if (res.error) {
        showMsg(res.error.message || "Save failed.", false);
        syncSave();
        return;
      }
      guides = guides.map(function (g) { return g.id === guide.id ? res.data : g; });
      editing = false;
      clearDirty();
      showMsg("Saved", true);
      setTimeout(function () { showMsg(""); }, 900);
      render();
    });
  }

  function seedIfNeeded() {
    var have = {};
    guides.forEach(function (g) {
      if (g.seed_key) have[g.seed_key] = true;
    });
    var missing = SEEDS.filter(function (seed) { return !have[seed.seed_key]; }).map(function (seed) {
      return {
        seed_key: seed.seed_key,
        title: seed.title,
        summary: seed.summary,
        category: seed.category,
        steps: seed.steps,
        link_title: seed.link_title,
        link_url: seed.link_url,
        sort_order: seed.sort_order
      };
    });
    if (!missing.length) return Promise.resolve();
    return db.from("sop_guides").insert(missing).select("*").then(function (res) {
      if (res.error) throw res.error;
      guides = guides.concat(res.data || []);
    });
  }

  function load() {
    showMsg("Loading SOPs…", true);
    return db.from("sop_guides").select("*").order("sort_order").then(function (res) {
      if (res.error) {
        showMsg(/does not exist|schema cache/i.test(res.error.message || "")
          ? "Run sql/010_sop.sql in Supabase, then refresh."
          : res.error.message, false);
        guides = [];
        render();
        return;
      }
      guides = res.data || [];
      return seedIfNeeded();
    }).then(function () {
      ensureSelection();
      clearDirty();
      showMsg("");
      render();
    }).catch(function (err) {
      showMsg((err && err.message) || "Could not load SOPs.", false);
      render();
    });
  }

  window.STLSOP = {
    mount: function (panel, client) {
      db = client;
      root = panel;
      selectedId = null;
      checkedSteps = {};
      editing = false;
      dirty = false;
      saving = false;
      panel.classList.add("sop-wide");
      panel.innerHTML = shell();
      syncSave();
      load();
    },
    unmount: function (panel) {
      hideSave();
      if (panel) panel.classList.remove("sop-wide");
      root = null;
    },
    saveAll: saveAll,
    isDirty: function () { return dirty; }
  };
})();
